import xml.etree.ElementTree as ET
import xml.dom.minidom
from tkinter import *
from tkinter import filedialog
import re


def setr004(block1, block2, block3, block4, block5):
    main = ET.Element('RedOrdr')

    branch_1 = ET.SubElement(main, 'MsgId')
    branch_1_sub_1 = ET.SubElement(branch_1, 'Id')
    branch_1_sub_2 = ET.SubElement(branch_1, 'CreDtTm')

    branch_2 = ET.SubElement(main, 'PoolRef')
    branch_2_sub_1 = ET.SubElement(branch_2, 'Ref')
    branch_2_sub_2 = ET.SubElement(branch_2, 'Reflssr')
    branch_2_sub_3 = ET.SubElement(branch_2, 'MsgNm')

    branch_3 = ET.SubElement(main, 'PrvsRef')
    branch_3_sub_1 = ET.SubElement(branch_3, 'Ref')
    branch_3_sub_2 = ET.SubElement(branch_3, 'Reflssr')
    branch_3_sub_3 = ET.SubElement(branch_3, 'MsgNm')

    branch_4 = ET.SubElement(main, 'MltplOrdrDtls')
    branch_4_sub_1 = ET.SubElement(branch_4, 'MstrRef')
    branch_4_sub_2 = ET.SubElement(branch_4, 'PlcOfTrad')
    branch_4_sub_2_sub_1 = ET.SubElement(branch_4_sub_2, 'Ctry')
    branch_4_sub_2_sub_2 = ET.SubElement(branch_4_sub_2, 'Xchg')
    branch_4_sub_2_sub_3 = ET.SubElement(branch_4_sub_2, 'Pty')
    branch_4_sub_2_sub_4 = ET.SubElement(branch_4_sub_2, 'OverTheCntr')
    branch_4_sub_3 = ET.SubElement(branch_4, 'OrdrDtTm')
    branch_4_sub_4 = ET.SubElement(branch_4, 'XpryDtTm')
    branch_4_sub_4_sub_1 = ET.SubElement(branch_4_sub_4, 'Dt')
    branch_4_sub_4_sub_2 = ET.SubElement(branch_4_sub_4, 'DtTm')
    branch_4_sub_5 = ET.SubElement(branch_4, 'ReqdFutrTradDt')
    branch_4_sub_6 = ET.SubElement(branch_4, 'CxlRght')
    branch_4_sub_6_sub_1 = ET.SubElement(branch_4_sub_6, 'Cd')
    branch_4_sub_6_sub_2 = ET.SubElement(branch_4_sub_6, 'Prtry')
    branch_4_sub_7 = ET.SubElement(branch_4, 'CxlRght')
    branch_4_sub_7_sub_1 = ET.SubElement(branch_4_sub_7, 'AcctId')
    branch_4_sub_7_sub_2 = ET.SubElement(branch_4_sub_7, 'AcctNm')
    branch_4_sub_7_sub_3 = ET.SubElement(branch_4_sub_7, 'AcctDsgnt')
    branch_4_sub_7_sub_4 = ET.SubElement(branch_4_sub_7, 'AcctDsgnt')
    branch_4_sub_7_sub_5 = ET.SubElement(branch_4_sub_7, 'AcctSvcr')
    branch_4_sub_7_sub_6 = ET.SubElement(branch_4_sub_7, 'OrdrOrgtrElgblty')
    branch_4_sub_7_sub_7 = ET.SubElement(branch_4_sub_7, 'SubAcctDtls')
    branch_4_sub_8 = ET.SubElement(branch_4, 'BnfcryDtls')
    branch_4_sub_8_sub_1 = ET.SubElement(branch_4_sub_8, 'Nm')
    branch_4_sub_8_sub_2 = ET.SubElement(branch_4_sub_8, 'BirthDt')
    branch_4_sub_8_sub_3 = ET.SubElement(branch_4_sub_8, 'CtryAndResdtlSts')
    branch_4_sub_8_sub_4 = ET.SubElement(branch_4_sub_8, 'OthrId')
    branch_4_sub_8_sub_5 = ET.SubElement(branch_4_sub_8, 'Id')
    branch_4_sub_8_sub_6 = ET.SubElement(branch_4_sub_8, 'IdTp')
    branch_4_sub_8_sub_7 = ET.SubElement(branch_4_sub_8, 'Cd')
    branch_4_sub_8_sub_8 = ET.SubElement(branch_4_sub_8, 'Prtry')
    branch_4_sub_8_sub_9 = ET.SubElement(branch_4_sub_8, 'Issr')
    branch_4_sub_9 = ET.SubElement(branch_4, 'IndvOrdrDtls')
    branch_4_sub_9_sub_1 = ET.SubElement(branch_4_sub_9, 'OrdrRef')
    branch_4_sub_9_sub_2 = ET.SubElement(branch_4_sub_9, 'ClntRef')
    branch_4_sub_9_sub_3 = ET.SubElement(branch_4_sub_9, 'OrdrTp')
    branch_4_sub_9_sub_3_sub_1 = ET.SubElement(branch_4_sub_9_sub_3, 'Cd')
    branch_4_sub_9_sub_3_sub_2 = ET.SubElement(branch_4_sub_9_sub_3, 'Prtry')
    branch_4_sub_9_sub_4 = ET.SubElement(branch_4_sub_9, 'FinInstrmDtls')
    branch_4_sub_9_sub_4_sub_1 = ET.SubElement(branch_4_sub_9_sub_4, 'Id')
    branch_4_sub_9_sub_4_sub_2 = ET.SubElement(branch_4_sub_9_sub_4, 'Nm')
    branch_4_sub_9_sub_4_sub_3 = ET.SubElement(branch_4_sub_9_sub_4, 'ShrtNm')
    branch_4_sub_9_sub_4_sub_4 = ET.SubElement(branch_4_sub_9_sub_4, 'SplmtryId')
    branch_4_sub_9_sub_4_sub_5 = ET.SubElement(branch_4_sub_9_sub_4, 'ClssTp')
    branch_4_sub_9_sub_4_sub_6 = ET.SubElement(branch_4_sub_9_sub_4, 'SctiesForm')
    branch_4_sub_9_sub_4_sub_7 = ET.SubElement(branch_4_sub_9_sub_4, 'DstrbtnPlcy')
    branch_4_sub_9_sub_4_sub_8 = ET.SubElement(branch_4_sub_9_sub_4, 'PdctGrp')
    branch_4_sub_9_sub_4_sub_9 = ET.SubElement(branch_4_sub_9_sub_4, 'SrsId')
    branch_4_sub_9_sub_4_sub_10 = ET.SubElement(branch_4_sub_9_sub_4, 'SrsDt')
    branch_4_sub_9_sub_4_sub_11 = ET.SubElement(branch_4_sub_9_sub_4, 'SrsNm')
    branch_4_sub_9_sub_5 = ET.SubElement(branch_4_sub_9, 'SubAcctForHldg')
    branch_4_sub_9_sub_5_sub_1 = ET.SubElement(branch_4_sub_9_sub_5, 'Id')
    branch_4_sub_9_sub_5_sub_2 = ET.SubElement(branch_4_sub_9_sub_5, 'Nm')
    branch_4_sub_9_sub_5_sub_3 = ET.SubElement(branch_4_sub_9_sub_5, 'Chrtc')
    branch_4_sub_9_sub_5_sub_4 = ET.SubElement(branch_4_sub_9_sub_5, 'AcctDsgnt')
    branch_4_sub_9_sub_6 = ET.SubElement(branch_4_sub_9, 'AmtOrUnitsOrPctg')
    branch_4_sub_9_sub_6_sub_1 = ET.SubElement(branch_4_sub_9_sub_6, 'UnitsNb')
    branch_4_sub_9_sub_6_sub_2 = ET.SubElement(branch_4_sub_9_sub_6, 'GrssAmt')
    branch_4_sub_9_sub_6_sub_3 = ET.SubElement(branch_4_sub_9_sub_6, 'NetAmt')
    branch_4_sub_9_sub_6_sub_4 = ET.SubElement(branch_4_sub_9_sub_6, 'HldgsRedRate')
    branch_4_sub_9_sub_7 = ET.SubElement(branch_4_sub_9, 'Rndg')
    branch_4_sub_9_sub_8 = ET.SubElement(branch_4_sub_9, 'SttlmAmt')
    branch_4_sub_9_sub_9 = ET.SubElement(branch_4_sub_9, 'CshSttlmDt')
    branch_4_sub_9_sub_10 = ET.SubElement(branch_4_sub_9, 'SttlmMtd')
    branch_4_sub_9_sub_11 = ET.SubElement(branch_4_sub_9, 'FXDtls')
    branch_4_sub_9_sub_12 = ET.SubElement(branch_4_sub_9, 'IncmPref')
    branch_4_sub_9_sub_13 = ET.SubElement(branch_4_sub_9, 'Grp1Or2Units')
    branch_4_sub_9_sub_14 = ET.SubElement(branch_4_sub_9, 'TxOvrhd')
    branch_4_sub_9_sub_14_sub_1 = ET.SubElement(branch_4_sub_9_sub_14, 'ComrclAgrmtRef')
    branch_4_sub_9_sub_14_sub_2 = ET.SubElement(branch_4_sub_9_sub_14, 'IndvFee')
    branch_4_sub_9_sub_14_sub_2_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'Tp')
    branch_4_sub_9_sub_14_sub_2_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_1, 'Cd')
    branch_4_sub_9_sub_14_sub_2_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_1, 'Prtry')
    branch_4_sub_9_sub_14_sub_2_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'Bsis')
    branch_4_sub_9_sub_14_sub_2_sub_2_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_2, 'Cd')
    branch_4_sub_9_sub_14_sub_2_sub_2_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_2, 'Prtry')
    branch_4_sub_9_sub_14_sub_2_sub_3 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'StdAmt')
    branch_4_sub_9_sub_14_sub_2_sub_4 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'StdRate')
    branch_4_sub_9_sub_14_sub_2_sub_5 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'DscntDtls')
    branch_4_sub_9_sub_14_sub_2_sub_5_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_5, 'Amt')
    branch_4_sub_9_sub_14_sub_2_sub_5_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_5, 'Rate')
    branch_4_sub_9_sub_14_sub_2_sub_5_sub_3 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_5, 'Bsis')
    branch_4_sub_9_sub_14_sub_2_sub_2_sub_3_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_5_sub_3, 'Cd')
    branch_4_sub_9_sub_14_sub_2_sub_2_sub_3_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_2_sub_5_sub_3, 'Prtry')
    branch_4_sub_9_sub_14_sub_2_sub_6 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'ReqdAmt')
    branch_4_sub_9_sub_14_sub_2_sub_7 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'ReqdRate')
    branch_4_sub_9_sub_14_sub_2_sub_8 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'NonStdSLARef')
    branch_4_sub_9_sub_14_sub_2_sub_9 = ET.SubElement(branch_4_sub_9_sub_14_sub_2, 'RcptId')
    branch_4_sub_9_sub_14_sub_3 = ET.SubElement(branch_4_sub_9_sub_14, 'IndvTax')
    branch_4_sub_9_sub_14_sub_3_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_3, 'Tp')
    branch_4_sub_9_sub_14_sub_3_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_1, 'Cd')
    branch_4_sub_9_sub_14_sub_3_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_1, 'Prtry')
    branch_4_sub_9_sub_14_sub_3_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_3, 'Tax')
    branch_4_sub_9_sub_14_sub_3_sub_2_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_2, 'Amt')
    branch_4_sub_9_sub_14_sub_3_sub_2_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_2, 'Rate')
    branch_4_sub_9_sub_14_sub_3_sub_3 = ET.SubElement(branch_4_sub_9_sub_14_sub_3, 'Ctry')
    branch_4_sub_9_sub_14_sub_3_sub_4 = ET.SubElement(branch_4_sub_9_sub_14_sub_3, 'XmptnInd')
    branch_4_sub_9_sub_14_sub_3_sub_5 = ET.SubElement(branch_4_sub_9_sub_14_sub_3, 'XmptnRsn')
    branch_4_sub_9_sub_14_sub_3_sub_5_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_5, 'Cd')
    branch_4_sub_9_sub_14_sub_3_sub_5_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_5, 'Prtry')
    branch_4_sub_9_sub_14_sub_3_sub_6 = ET.SubElement(branch_4_sub_9_sub_14_sub_3, 'RcptId')
    branch_4_sub_9_sub_14_sub_3_sub_7 = ET.SubElement(branch_4_sub_9_sub_14_sub_3, 'TaxClctnDtls')
    branch_4_sub_9_sub_14_sub_3_sub_7_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_5, 'Bsis')
    branch_4_sub_9_sub_14_sub_3_sub_7_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_7_sub_1, 'Cd')
    branch_4_sub_9_sub_14_sub_3_sub_7_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_14_sub_3_sub_7_sub_1, 'Prtry')
    branch_4_sub_9_sub_15 = ET.SubElement(branch_4_sub_9, 'SttlmAndCtdyDtls')
    branch_4_sub_9_sub_15_sub_1 = ET.SubElement(branch_4_sub_9_sub_15, 'SttlmDt')
    branch_4_sub_9_sub_15_sub_2 = ET.SubElement(branch_4_sub_9_sub_15, 'SttlmPlc')
    branch_4_sub_9_sub_15_sub_3 = ET.SubElement(branch_4_sub_9_sub_15, 'SfkpgPlc')
    branch_4_sub_9_sub_15_sub_4 = ET.SubElement(branch_4_sub_9_sub_15, 'SctiesSttlmSysId')
    branch_4_sub_9_sub_15_sub_5 = ET.SubElement(branch_4_sub_9_sub_15, 'TradTxCond')
    branch_4_sub_9_sub_15_sub_6 = ET.SubElement(branch_4_sub_9_sub_15, 'SttlmTxCond')
    branch_4_sub_9_sub_15_sub_7 = ET.SubElement(branch_4_sub_9_sub_15, 'RcvgSdDtls')
    branch_4_sub_9_sub_15_sub_7_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_7, 'RcvgSdDtls')
    branch_4_sub_9_sub_15_sub_7_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_1, 'PtyId')
    branch_4_sub_9_sub_15_sub_7_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_1, 'AcctId')
    branch_4_sub_9_sub_15_sub_7_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_7, 'RcvrsIntrmy1Dtls')
    branch_4_sub_9_sub_15_sub_7_sub_2_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_2, 'PtyId')
    branch_4_sub_9_sub_15_sub_7_sub_2_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_2, 'AcctId')
    branch_4_sub_9_sub_15_sub_7_sub_3 = ET.SubElement(branch_4_sub_9_sub_15_sub_7, 'RcvrsIntrmy2Dtls')
    branch_4_sub_9_sub_15_sub_7_sub_3_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_3, 'PtyId')
    branch_4_sub_9_sub_15_sub_7_sub_3_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_3, 'AcctId')
    branch_4_sub_9_sub_15_sub_7_sub_4 = ET.SubElement(branch_4_sub_9_sub_15_sub_7, 'RcvgAgtDtls')
    branch_4_sub_9_sub_15_sub_7_sub_4_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_4, 'PtyId')
    branch_4_sub_9_sub_15_sub_7_sub_4_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_7_sub_4, 'AcctId')
    branch_4_sub_9_sub_15_sub_8 = ET.SubElement(branch_4_sub_9_sub_15, 'DlvrgSdDtls')
    branch_4_sub_9_sub_15_sub_8_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_8, 'DlvrrsCtdnDtls')
    branch_4_sub_9_sub_15_sub_8_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_1, 'PtyId')
    branch_4_sub_9_sub_15_sub_8_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_1, 'AcctId')
    branch_4_sub_9_sub_15_sub_8_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_8, 'DlvrrsIntrmy1Dtls')
    branch_4_sub_9_sub_15_sub_8_sub_2_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_2, 'PtyId')
    branch_4_sub_9_sub_15_sub_8_sub_2_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_2, 'AcctId')
    branch_4_sub_9_sub_15_sub_8_sub_3 = ET.SubElement(branch_4_sub_9_sub_15_sub_8, 'DlvrrsIntrmy2Dtls')
    branch_4_sub_9_sub_15_sub_8_sub_3_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_3, 'PtyId')
    branch_4_sub_9_sub_15_sub_8_sub_3_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_3, 'AcctId')
    branch_4_sub_9_sub_15_sub_8_sub_4 = ET.SubElement(branch_4_sub_9_sub_15_sub_8, 'DlvrgAgtDtls')
    branch_4_sub_9_sub_15_sub_8_sub_4_sub_1 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_4, 'PtyId')
    branch_4_sub_9_sub_15_sub_8_sub_4_sub_2 = ET.SubElement(branch_4_sub_9_sub_15_sub_8_sub_4, 'AcctId')
    branch_4_sub_9_sub_16 = ET.SubElement(branch_4_sub_9, 'PhysDlvryInd')
    branch_4_sub_9_sub_17 = ET.SubElement(branch_4_sub_9, 'PhysDlvryDtls')
    branch_4_sub_9_sub_16_sub_1 = ET.SubElement(branch_4_sub_9_sub_17, 'Adr')
    branch_4_sub_9_sub_16_sub_2 = ET.SubElement(branch_4_sub_9_sub_17, 'IssdCertNb')
    branch_4_sub_9_sub_18 = ET.SubElement(branch_4_sub_9, 'ReqdSttlmCcy')
    branch_4_sub_9_sub_19 = ET.SubElement(branch_4_sub_9, 'ReqdNAVCcy')
    branch_4_sub_9_sub_20 = ET.SubElement(branch_4_sub_9, 'CshSttlmDtls')
    branch_4_sub_9_sub_20_sub_1 = ET.SubElement(branch_4_sub_9_sub_20, 'PmtInstrm')
    branch_4_sub_9_sub_20_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_20_sub_1, 'CdtTrfDtls')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'Ref')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'Dbtr')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_3 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'DbtrAcct')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_4 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'DbtrAgt')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_5 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'DbtrAgtAcct')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_6 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'IntrmyAgt1')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_7 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'IntrmyAgt1Acct')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_8 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'IntrmyAgt2')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_9 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'IntrmyAgt2Acct')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_10 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'CdtrAgt')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_11 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'CdtrAgtAcct')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_12 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'Cdtr')
    branch_4_sub_9_sub_20_sub_1_sub_1_sub_13 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_1, 'CdtrAcct')
    branch_4_sub_9_sub_20_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_20_sub_1, 'ChqDtls')
    branch_4_sub_9_sub_20_sub_1_sub_2_sub_1 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_2, 'Nb')
    branch_4_sub_9_sub_20_sub_1_sub_2_sub_2 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_2, 'PyeeId')
    branch_4_sub_9_sub_20_sub_1_sub_2_sub_3 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_2, 'DrweeId')
    branch_4_sub_9_sub_20_sub_1_sub_2_sub_4 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_2, 'DrwrId')
    branch_4_sub_9_sub_20_sub_1_sub_3 = ET.SubElement(branch_4_sub_9_sub_20_sub_1, 'BkrsDrftDtls')
    branch_4_sub_9_sub_20_sub_1_sub_3_sub_1 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_3, 'Nb')
    branch_4_sub_9_sub_20_sub_1_sub_3_sub_2 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_3, 'PyeeId')
    branch_4_sub_9_sub_20_sub_1_sub_3_sub_3 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_3, 'DrweeId')
    branch_4_sub_9_sub_20_sub_1_sub_3_sub_4 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_3, 'DrwrId')
    branch_4_sub_9_sub_20_sub_1_sub_4 = ET.SubElement(branch_4_sub_9_sub_20_sub_1, 'CshAcctDtls')
    branch_4_sub_9_sub_20_sub_1_sub_4_sub_1 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_4, 'AcctId')
    branch_4_sub_9_sub_20_sub_1_sub_4_sub_2 = ET.SubElement(branch_4_sub_9_sub_20_sub_1_sub_4, 'Tp')
    branch_4_sub_9_sub_21 = ET.SubElement(branch_4_sub_9, 'StffClntBrkdwn')
    branch_4_sub_9_sub_21_sub_1 = ET.SubElement(branch_4_sub_9_sub_21, 'OrdrBrkdwnTp')
    branch_4_sub_9_sub_21_sub_2 = ET.SubElement(branch_4_sub_9_sub_21, 'Cd')
    branch_4_sub_9_sub_21_sub_3 = ET.SubElement(branch_4_sub_9_sub_21, 'Prtry')
    branch_4_sub_9_sub_21_sub_4 = ET.SubElement(branch_4_sub_9_sub_21, 'Amt')
    branch_4_sub_9_sub_22 = ET.SubElement(branch_4_sub_9, 'FinAdvc')
    branch_4_sub_9_sub_23 = ET.SubElement(branch_4_sub_9, 'NgtdTrad')
    branch_4_sub_9_sub_24 = ET.SubElement(branch_4_sub_9, 'RltdPtyDtls')
    branch_4_sub_9_sub_24_sub_1 = ET.SubElement(branch_4_sub_9_sub_24, 'Id')
    branch_4_sub_9_sub_24_sub_2 = ET.SubElement(branch_4_sub_9_sub_24, 'Acct')
    branch_4_sub_9_sub_24_sub_2_sub_1 = ET.SubElement(branch_4_sub_9_sub_24_sub_2, 'Id')
    branch_4_sub_9_sub_24_sub_2_sub_2 = ET.SubElement(branch_4_sub_9_sub_24_sub_2, 'AcctSvcr')
    branch_4_sub_9_sub_24_sub_3 = ET.SubElement(branch_4_sub_9_sub_24, 'OrdrOrgtrElgblty')
    branch_4_sub_9_sub_24_sub_4 = ET.SubElement(branch_4_sub_9_sub_24, 'Role')
    branch_4_sub_9_sub_25 = ET.SubElement(branch_4_sub_9, 'Equlstn')
    branch_4_sub_9_sub_25_sub_1 = ET.SubElement(branch_4_sub_9_sub_25, 'Amt')
    branch_4_sub_9_sub_25_sub_2 = ET.SubElement(branch_4_sub_9_sub_25, 'Rate')
    branch_4_sub_9_sub_26 = ET.SubElement(branch_4_sub_9, 'CstmrCndctClssfctn')
    branch_4_sub_9_sub_26_sub_1 = ET.SubElement(branch_4_sub_9_sub_26, 'Cd')
    branch_4_sub_9_sub_26_sub_2 = ET.SubElement(branch_4_sub_9_sub_26, 'Prtry')
    branch_4_sub_9_sub_27 = ET.SubElement(branch_4_sub_9, 'TxChanlTp')
    branch_4_sub_9_sub_27_sub_1 = ET.SubElement(branch_4_sub_9_sub_27, 'Cd')
    branch_4_sub_9_sub_27_sub_2 = ET.SubElement(branch_4_sub_9_sub_27, 'Prtry')
    branch_4_sub_9_sub_28 = ET.SubElement(branch_4_sub_9, 'SgntrTp')
    branch_4_sub_9_sub_28_sub_1 = ET.SubElement(branch_4_sub_9_sub_28, 'Cd')
    branch_4_sub_9_sub_28_sub_2 = ET.SubElement(branch_4_sub_9_sub_28, 'Prtry')
    branch_4_sub_9_sub_29 = ET.SubElement(branch_4_sub_9, 'OrdrWvrDtls')
    branch_4_sub_9_sub_29_sub_1 = ET.SubElement(branch_4_sub_9_sub_29, 'OrdrWvrRsn')
    branch_4_sub_9_sub_29_sub_1_sub_1 = ET.SubElement(branch_4_sub_9_sub_29_sub_1, 'Cd')
    branch_4_sub_9_sub_29_sub_1_sub_2 = ET.SubElement(branch_4_sub_9_sub_29_sub_1, 'Prtry')
    branch_4_sub_9_sub_29_sub_2 = ET.SubElement(branch_4_sub_9_sub_29, 'InfVal')
    branch_4_sub_10 = ET.SubElement(branch_4, 'BlkCshSttlmDtls')
    branch_4_sub_10_sub_1 = ET.SubElement(branch_4_sub_10, 'PmtInstrm')
    branch_4_sub_10_sub_1_sub_1 = ET.SubElement(branch_4_sub_10_sub_1, 'CdtTrfDtls')
    branch_4_sub_10_sub_2_sub_1_sub_1 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'Ref')
    branch_4_sub_10_sub_2_sub_1_sub_2 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'Dbtr')
    branch_4_sub_10_sub_2_sub_1_sub_3 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'DbtrAcct')
    branch_4_sub_10_sub_2_sub_1_sub_4 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'DbtrAgt')
    branch_4_sub_10_sub_2_sub_1_sub_5 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'DbtrAgtAcct')
    branch_4_sub_10_sub_2_sub_1_sub_6 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'IntrmyAgt1')
    branch_4_sub_10_sub_2_sub_1_sub_7 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'IntrmyAgt1Acct')
    branch_4_sub_10_sub_2_sub_1_sub_8 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'IntrmyAgt2')
    branch_4_sub_10_sub_2_sub_1_sub_9 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'IntrmyAgt2Acct')
    branch_4_sub_10_sub_2_sub_1_sub_10 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'CdtrAgt')
    branch_4_sub_10_sub_2_sub_1_sub_11 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'CdtrAgtAcct')
    branch_4_sub_10_sub_2_sub_1_sub_12 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'Cdtr')
    branch_4_sub_10_sub_2_sub_1_sub_13 = ET.SubElement(branch_4_sub_10_sub_1_sub_1, 'CdtrAcct')
    branch_4_sub_10_sub_1_sub_2 = ET.SubElement(branch_4_sub_10_sub_1, 'ChqDtls')
    branch_4_sub_10_sub_2_sub_2_sub_1 = ET.SubElement(branch_4_sub_10_sub_1_sub_2, 'Nb')
    branch_4_sub_10_sub_2_sub_2_sub_2 = ET.SubElement(branch_4_sub_10_sub_1_sub_2, 'PyeeId')
    branch_4_sub_10_sub_2_sub_2_sub_3 = ET.SubElement(branch_4_sub_10_sub_1_sub_2, 'DrweeId')
    branch_4_sub_10_sub_2_sub_2_sub_4 = ET.SubElement(branch_4_sub_10_sub_1_sub_2, 'DrwrId')
    branch_4_sub_10_sub_1_sub_3 = ET.SubElement(branch_4_sub_10_sub_1, 'BkrsDrftDtls')
    branch_4_sub_10_sub_2_sub_3_sub_1 = ET.SubElement(branch_4_sub_10_sub_1_sub_3, 'Nb')
    branch_4_sub_10_sub_2_sub_3_sub_2 = ET.SubElement(branch_4_sub_10_sub_1_sub_3, 'PyeeId')
    branch_4_sub_10_sub_2_sub_3_sub_3 = ET.SubElement(branch_4_sub_10_sub_1_sub_3, 'DrweeId')
    branch_4_sub_10_sub_2_sub_3_sub_4 = ET.SubElement(branch_4_sub_10_sub_1_sub_3, 'DrwrId')
    branch_4_sub_10_sub_1_sub_4 = ET.SubElement(branch_4_sub_10_sub_1, 'CshAcctDtls')
    branch_4_sub_10_sub_2_sub_4_sub_1 = ET.SubElement(branch_4_sub_10_sub_1_sub_4, 'Acctld')
    branch_4_sub_10_sub_2_sub_4_sub_2 = ET.SubElement(branch_4_sub_10_sub_1_sub_4, 'Tp')
    branch_4_sub_11 = ET.SubElement(branch_4, 'TtlSttlmAmt')

    branch_5 = ET.SubElement(main, 'CpyDtls')
    branch_5_sub_1 = ET.SubElement(branch_5, 'CpyInd')
    branch_5_sub_2 = ET.SubElement(branch_5, 'OrgnlRcvr')

    branch_6 = ET.SubElement(main, 'Xtnsn')
    branch_6_sub_1 = ET.SubElement(branch_6, 'PlcAndNm')
    branch_6_sub_2 = ET.SubElement(branch_6, 'Txt')

    for tags in block4:
        if tags[1:4] == '11A':
            branch_6_sub_2.text = tags[5:]

    final_xml(ET.tostring(main))


def final_xml(xml_string):
    dom = xml.dom.minidom.parseString(xml_string)
    output_xml = dom.toprettyxml()
    print(output_xml)


def openFile():
    filepath = filedialog.askopenfilename()
    file = open(filepath, 'r')
    read = file.readlines()

    list_tags = ['11A', '12a', '13a', '16R', '16S',
                 '17B', '19A', '20C', '22F', '22a',
                 '23G', '35B', '36B', '70a', '70E',
                 '70C', '90a', '92A', '92B', '92a',
                 '94a', '94B', '95a', '97a', '98a',
                 '98A', '99B']
    list_character = ['{',
                      ':',
                      '-']
    list_content_block1 = []
    list_content_block2 = []
    list_content_block3 = []
    list_content_block4 = []
    list_content_block5 = []
    list_main = []

    list_content_line1 = re.findall(r'{([^{}]+)}', read[0])

    for block in list_content_line1:
        if block[0:2] == '1:':
            list_content_block1.append(block[:])
        elif block[0:2] == '2:':
            list_content_block2.append(block[:])

    list_content_block3.append(list_content_line1[2] + ' ' + list_content_line1[3])

    for line in read:
        if line[1:4] in list_tags:
            list_content_block4.append(line[:])
        elif line[0] not in list_character:
            if len(list_content_block4) != 0:
                list_content_block4[-1] += line

    for character in read:
        if character[0] == '-':
            list_content_block5.append(character[3:])

    appID = list_content_block1[0][2:3]
    serviceID = list_content_block1[0][3:5]
    BIC8 = list_content_block1[0][5:13]
    BIC11 = list_content_block1[0][5:16]
    print(appID)
    print(serviceID)
    print(BIC8)
    print(BIC11)

    print(list_content_block1)
    print(list_content_block2)
    print(list_content_block3)
    print(list_content_block4)
    print(list_content_block5)
    # setr004(list_content_block1, list_content_block2, list_content_block3, list_content_block4, list_content_block5)


window = Tk()
button = Button(text="open", command=openFile)
button.pack()
window.mainloop()
openFile()
